// <auto-generated />
using AlbionFoodCalculator.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AlbionFoodCalculator.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AlbionFoodCalculator.Models.FoodItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("CraftingFocus")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("AlbionFoodCalculator.Models.FoodItemResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("FoodItemName")
                        .HasColumnType("text");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemName");

                    b.HasIndex("ResourceName");

                    b.ToTable("FoodItemResources");
                });

            modelBuilder.Entity("AlbionFoodCalculator.Models.Resource", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("AlbionFoodCalculator.Models.FoodItemResource", b =>
                {
                    b.HasOne("AlbionFoodCalculator.Models.FoodItem", "FoodItem")
                        .WithMany("Resourses")
                        .HasForeignKey("FoodItemName");

                    b.HasOne("AlbionFoodCalculator.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceName");
                });
#pragma warning restore 612, 618
        }
    }
}
