query FoodItem($name: String!, $city: String!) {
  foodItem(name: $name, city: $city) {
    name
    craftingFocus
    maximalBuyPrice
    maximalBuyPriceDate
    minimalSellPrice
    minimalSellPriceDate
  }
}
